[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'pum.vim', 'context_filetype.vim']
on_event = ['InsertEnter', 'CursorHold', 'CmdlineEnter']
lua_add = '''
    local ddc = require('rc.ddc')
    ddc.set_source_options('_', {
        ignoreCase = true,
        matchers = { 'matcher_fuzzy' },
        sorters = { 'sorter_fuzzy' },
        converters = { 'converter_fuzzy' },
    })
    ddc.enable_cmdline_completion_with(':', function(cmap, pum)
        cmap('<Tab>', function()
            return pum.visible() and pum.map.insert_relative(1, "loop") or ddc.map.manual_complete()
        end)
        cmap({ '<C-n>', '<Down>' }, function()
            return pum.visible() and pum.map.insert_relative(-1, "loop") or '<Down>'
        end)
        cmap({ '<C-p>', '<Up>' }, function()
            return pum.visible() and pum.map.insert_relative(1, "loop") or '<Up>'
        end)
        cmap('<CR>', function()
            if pum.visible() and pum.complete_info().selected ~= -1 then
                return pum.map.confirm()
            else
                return '<CR>'
            end
        end)
    end)
'''
lua_source = '''
    local ddc = require('rc.ddc')

    ddc.custom.patch_global({
        ui = 'pum',
        sources = { 'around', 'skkeleton' },
        cmdlineSources = { 'cmdline', 'cmdline-history', 'around' },
        sourceOptions = ddc.get_source_options(),
        sourceParams = ddc.get_source_params(),
        autoCompleteEvents = { 'InsertEnter', 'TextChangedI', 'TextChangedP', 'CmdlineEnter', 'CmdlineChanged' },
        backspaceCompletion = true,
    })
    ddc.custom.patch_filetype({ 'vim', 'typescript', 'typescriptreact', 'astro', 'rust', 'javascript' }, {
        sources = { 'vsnip', 'lsp', 'around' },
    })
    ddc.custom.patch_filetype({ 'awk', 'c', 'cpp', 'cs', 'dart', 'go', 'haskell', 'python', 'ruby', 'lua' , 'nil', 'typst' }, {
        sources = { 'lsp', 'around' },
    })
    ddc.custom.patch_filetype({ 'lean' }, {
        sources = { 'lsp', 'around' },
        sourceOptions = { ['lsp'] = { minAutoCompleteLength = 1 } },
    })
    ddc.custom.patch_filetype({ 'css', 'scss' }, {
        sources = { 'lsp' },
    })
    ddc.custom.patch_filetype({ 'tex' }, {
        sources = { 'lsp', 'vsnip', 'around', 'skkeleton' },
        sourceOptions = {
            ['vsnip'] = { minAutoCompleteLength = 1 },
            ['lsp'] = {
                minAutoCompleteLength = 3,
                matchers = { 'matcher_head' }
            },
        },
    })
    ddc.custom.patch_filetype({ 'markdown' }, {
        sources = { 'around', 'mocword' },
    })
    ddc.custom.patch_filetype({ 'pdf', 'mips' }, {
        sources = { 'vsnip', 'around' },
    })
    ddc.custom.patch_filetype({ 'ddu-ff-filter' }, {
        specialBufferCompletion = false,
    })

    vim.cmd [[
      call ddc#custom#set_context_global({ ->
        \ ddc#syntax#in('comment') ? #{
        \   sources: ['around', 'mocword'],
        \ } : {} })
      " Partedit で補完ができるように
      autocmd OptionSet buftype if &buftype ==# 'acwrite' | call ddc#custom#patch_buffer('specialBufferCompletion', v:true) | endif
    ]]

    ddc.enable()
'''

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'
lua_source = '''
    require('rc.ddc').set_source_options('around', {
        mark = ' ',
        matchers = { 'matcher_head', 'matcher_length' },
        converters = { 'converter_remove_overlap' },
    })
    require('rc.ddc').set_source_params('around', {
        maxSize = 500
    })
'''

[[plugins]]
repo = 'Shougo/ddc-source-mocword'
on_source = 'ddc.vim'
lua_source = '''
    require('rc.ddc').set_source_options('mocword', {
        mark = ' ',
        matchers = { 'matcher_head', 'matcher_length' },
        converters = { 'converter_remove_overlap' },
        isVolatile = true,
        minAutoCompleteLength = 1,
    })
'''

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
on_source = 'ddc.vim'
depends = 'vim-vsnip'
lua_source = '''
    require('rc.ddc').set_source_options('lsp', {
        mark = ' ',
        dup = 'keep',
        -- forceCompletionPattern = [[\.\w*|:\w*|->\w*]],
    })
    require('rc.ddc').set_source_params('lsp', {
        snippetEngine = vim.fn['denops#callback#register'](function(body)
          vim.fn['vsnip#anonymous'](body)
        end),
        enableResolveItem = true,
        enableAdditionalTextEdit = true
    })
'''

[[plugins]]
repo = 'uga-rosa/ddc-source-lsp-setup'
on_source = 'ddc.vim'
lua_source = '''
    require("ddc_source_lsp_setup").setup {
        override_capabilities = false,
        respect_trigger = true
    }
'''

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'
on_source = 'ddc.vim'
lua_source = '''
    require('rc.ddc').set_source_options('cmdline', {
        mark = ' ',
        minAutoCompleteLength = 1,
    })
'''

[[plugins]]
repo = 'Shougo/ddc-source-cmdline-history'
on_source = 'ddc.vim'
lua_source = '''
    require('rc.ddc').set_source_options('cmdline-history', {
        mark = ' ',
        matchers = { 'matcher_head', 'matcher_length' },
        converters = { 'converter_remove_overlap' },
    })
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_source = 'ddc.vim'
lua_add = '''
    vim.g.vsnip_snippet_dir = vim.fn.expand('~/dotfiles/vim/snippet')
    vim.keymap.set('i', '<Tab>', function()
        return vim.fn['vsnip#jumpable'](1) ~= 0 and '<Plug>(vsnip-jump-next)' or '<Tab>'
    end, { expr = true })
    vim.keymap.set('i', '<S-Tab>', function()
        return vim.fn['vsnip#jumpable'](-1) ~= 0 and '<Plug>(vsnip-jump-prev)' or '<S-Tab>'
    end, { expr = true })
'''

[[plugins]]
repo = 'uga-rosa/ddc-source-vsnip'
on_source = 'ddc.vim'
depends = 'vim-vsnip'
lua_source = '''
    require('rc.ddc').set_source_options('vsnip', {
        mark = ' ',
        dup = 'keep',
    })
'''

[[plugins]]
repo = 'vim-skk/skkeleton'
on_source = 'ddc.vim'
lua_source = '''
    require('rc.ddc').set_source_options('skkeleton', {
        mark = ' ',
        matchers = { 'matcher_head', 'matcher_length' },
        converters = { 'converter_remove_overlap' },
        isVolatile = true,
        minAutoCompleteLength = 2,
    })
    vim.fn['skkeleton#config']({
        globalDictionaries = { '~/.local/share/SKK/dict/SKK-JISYO.L' },
        eggLikeNewline = true,
        registerConvertResult = true,
    })
    vim.keymap.set({ 'i', 'c' }, '<C-j>', '<Plug>(skkeleton-enable)')
'''

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_source = 'ddc.vim'

[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_length'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_remove_overlap'
on_source = 'ddc.vim'

# [[plugins]]
# repo = 'uga-rosa/ddc-previewer-floating'
# on_source = 'ddc.vim'
# lua_source = 'require("ddc_previewer_floating").enable()'

[[plugins]]
repo = 'matsui54/denops-signature_help'
on_source = 'ddc.vim'
hook_source = 'call signature_help#enable()'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'ddc.vim'
hook_source = 'call popup_preview#enable()'
