[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  let s:github_pat = expand('~/dotfiles/vim/github_parsonal_access_token.txt')
  if filereadable(s:github_pat)
    let g:dein#install_github_api_token = readfile(s:github_pat)[0]
    command! UpdatePlugin call dein#check_update(v:true)
  endif
'''

[[plugins]]
repo = 'ryota2357/dein-snip.lua'

[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
  let g:denops_server_addr = '127.0.0.1:32123'
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = 'set helplang=ja,en'

[[plugins]]
repo = 'lambdalisue/kensaku.vim'
depends = 'denops.vim'

[[plugins]]
repo = 'RRethy/vim-illuminate'

[[plugins]]
repo = 'ryota2357/necodark'
rev = 'build/nvim'
hook_add = 'colorscheme necodark'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'EdenEast/nightfox.nvim'

[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
repo = 'tomasiser/vim-code-dark'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
  let g:context_filetype#ignore_patterns = #{
    \ toml: ['^\s*#\s*'],
    \ }
'''

[[plugins]]
repo = 'harenome/vim-mipssyntax'

[[plugins]]
repo = 'monaqa/dial.nvim'
hook_add = '''
  nnoremap  <C-a>  <Plug>(dial-increment)
  nnoremap  <C-x>  <Plug>(dial-decrement)
  nnoremap g<C-a> g<Plug>(dial-increment)
  nnoremap g<C-x> g<Plug>(dial-decrement)
  vnoremap  <C-a>  <Plug>(dial-increment)
  vnoremap  <C-x>  <Plug>(dial-decrement)
  vnoremap g<C-a> g<Plug>(dial-increment)
  vnoremap g<C-x> g<Plug>(dial-decrement)
'''
