[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  let g:dein#enable_notification = v:true
'''

[[plugins]]
repo = 'rcarriga/nvim-notify'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja,en
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'

# [[plugins]]
# repo = 'ryota2357/vim-mycolors'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  syntax on
  colorscheme onedark
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
  vnoremap ? :'<,'>TComment<CR>
  nnoremap ? V:'<,'>TComment<CR>
'''

# 末尾の空白が赤で強調表示する
# 空白を削除する → FixWhitespac
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
  let g:extra_whitespace_ignored_filetypes = ['markdown', 'defx']
'''

# コマンド :Inspecthi
[[plugins]]
repo = 'cocopon/inspecthi.vim'

# markdown preview
# コマンド :PreviewMarkdown       # Start the preview
#          :PreviewMarkdownStop   # Stop the preview
#          :PreviewMarkdownToggle # Toggle the window
[[plugins]]
repo = 'kat0h/bufpreview.vim'


# fzf
[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = './install --all'
merged = 0
hook_add = '''
  set rtp+=/usr/local/opt/fzf
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   'rg --column --line-number --hidden --ignore-case --no-heading --color=always '.shellescape(<q-args>), 1,
    \   <bang>0 ? fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%')
    \           : fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'right:50%:hidden', '?'),
    \   <bang>0)
  command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)
  nnoremap <Leader>g :Rg<CR>
  nnoremap <Leader>f :Files<CR>
  nnoremap <Leader>F :GFiles<CR>
  nnoremap <Leader>h :History<CR>
'''

# [[plugins]]
# repo = '~/CompetitiveProgramming/Library/cpl'
