[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
let s:github_pat = expand('~/dotfiles/vim/github_parsonal_access_token.txt')
if filereadable(s:github_pat)
  let g:dein#install_github_api_token = readfile(s:github_pat)[0]
  command! UpdatePlugin call dein#check_update(v:true)
endif
'''

[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
  let g:denops_server_addr = '127.0.0.1:32123'
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja,en
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  syntax on
  colorscheme onedark
'''

# 末尾の空白が赤で強調表示する
# 空白を削除する → FixWhitespace
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
  let g:extra_whitespace_ignored_filetypes = ['markdown', 'defx']
'''
