[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  let g:dein#enable_notification = v:true
  let g:dein#install_progress_type = 'floating'
  "let g:dein#auto_recache = v:true
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja,en
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  syntax on
  colorscheme onedark
'''

# 末尾の空白が赤で強調表示する
# 空白を削除する → FixWhitespace
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
  let g:extra_whitespace_ignored_filetypes = ['markdown', 'defx']
'''
