hook_add = '''
'''

[ftplugin]
tex = '''
  setlocal tabstop=2 softtabstop=2 shiftwidth=2
  setlocal sidescrolloff=10
  setlocal foldmarker=!!!>,<!!!

  inoremap <buffer>$ $$<Left>
  inoremap <buffer>' '

  autocmd BufWritePre *.tex :call FixPunctuation()
  function! FixPunctuation() abort
    let l:pos = getpos('.')
    silent! execute ':%s/。/. /g'
    silent! execute ':%s/、/, /g'
    silent! execute ':%s/\\\@<!\s\+$//'
    call setpos('.', l:pos)
  endfunction
'''
typescript = '''
  setlocal tabstop=2 softtabstop=2 shiftwidth=2
  inoremap <buffer>` ``<Left>
'''
dart = '''
  setlocal tabstop=2 softtabstop=2 shiftwidth=2
'''
