hook_add = '''
'''

[ftplugin]
tex = '''
  inoremap <buffer> $ $$<Left>

  " 日本語は2文字分だから通常の2倍に
  setlocal sidescrolloff=10

  " 規定だと\frac{abs{sin{x}}}{2}とかに引っかかる
  setlocal foldmarker=!!!>,<!!!

  autocmd BufWritePre *.tex :call FixPunctuation()

  function! FixPunctuation() abort
    try
      :%s/。/. /g
    catch
    endtry
    try
      :%s/、/, /g
    catch
    endtry
    :FixWhitespace  " bronson/vim-trailing-whitespace
  endfunction
'''
