hook_add = '''
'''

[ftplugin]
tex = '''
  inoremap <buffer> $ $$<Left>

  " 日本語は2文字分だから通常の2倍に
  setlocal sidescrolloff=10

  " 規定だと\frac{abs{sin{x}}}{2}とかに引っかかる
  setlocal foldmarker=!!!>,<!!!

  autocmd BufWritePre *.tex :call FixPunctuation()

  function! FixPunctuation() abort
    let l:pos = getpos(".")
    silent! execute ':%s/。/. /g'
    silent! execute ':%s/、/, /g'
    silent! execute ':%s/\\\@<!\s\+$//'
    call setpos(".", l:pos)
  endfunction
'''
