hook_add = '''
  let g:tex_flavor = 'latex'
  autocmd BufRead CMakeLists.txt set filetype=cmake
'''

[ftplugin]
help = '''
  setlocal nolist
  setlocal noexpandtab
  setlocal tabstop=8 softtabstop=8 shiftwidth=8
'''
qf = '''
  nnoremap <buffer><ESC> <Cmd>close<CR>
  setlocal cmdheight=0
'''
tex = '''
  setlocal tabstop=2 softtabstop=2 shiftwidth=2
  setlocal sidescrolloff=10
  setlocal foldmarker=!!!>,<!!!
  autocmd BufWritePre *.tex :call FixPunctuation()
  function! FixPunctuation() abort
    let l:pos = getpos('.')
    silent! execute ':%s/。/. /g'
    silent! execute ':%s/、/, /g'
    silent! execute ':%s/\\\@<!\s\+$//'
    call setpos('.', l:pos)
  endfunction
'''
make = '''
  setlocal noexpandtab
  setlocal tabstop=6 softtabstop=6 shiftwidth=6
'''
mips = '''
  setlocal noexpandtab
  setlocal tabstop=4 softtabstop=4 shiftwidth=4
'''
