hook_add = '''
  let g:tex_flavor = 'latex'
  autocmd BufRead CMakeLists.txt set filetype=cmake
'''

[ftplugin]
tex = '''
  setlocal tabstop=2 softtabstop=2 shiftwidth=2
  setlocal sidescrolloff=10
  setlocal foldmarker=!!!>,<!!!
  autocmd BufWritePre *.tex :call FixPunctuation()
  function! FixPunctuation() abort
    let l:pos = getpos('.')
    silent! execute ':%s/。/. /g'
    silent! execute ':%s/、/, /g'
    silent! execute ':%s/\\\@<!\s\+$//'
    call setpos('.', l:pos)
  endfunction
'''
typescript = '''
  setlocal tabstop=2 softtabstop=2 shiftwidth=2
'''
scss = '''
  setlocal tabstop=2 softtabstop=2 shiftwidth=2
'''
dart = '''
  setlocal tabstop=2 softtabstop=2 shiftwidth=2
'''
json = '''
  setlocal tabstop=2 softtabstop=2 shiftwidth=2
'''
vim = '''
  setlocal tabstop=2 softtabstop=2 shiftwidth=2
'''
pdf = '''
  setlocal tabstop=2 softtabstop=2 shiftwidth=2
'''
help = '''
  setlocal nolist
  setlocal noexpandtab
  setlocal tabstop=8 softtabstop=8 shiftwidth=8
'''
make = '''
  setlocal noexpandtab
  setlocal tabstop=6 softtabstop=6 shiftwidth=6
'''
