[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['mason.nvim', 'mason-lspconfig.nvim']
on_event = 'BufReadPost'
hook_add = '''
  autocmd BufWritePre *.ts,*.dart,*.rs lua vim.lsp.buf.format()
  command! Format lua vim.lsp.buf.format()
'''
hook_source = '''
lua << EOF
  local nvim_lsp = require('lspconfig')
  local mason = require('mason')
  local mason_lspconfig = require('mason-lspconfig')
  local util = require('lspconfig.util')

  local signs = { Error = "", Warn = "", Hint = "", Info = "" }
  for type, icon in pairs(signs) do
    local hl = "DiagnosticSign" .. type
    vim.fn.sign_define(hl, { text = icon, texthl = hl, numhl = hl })
  end

  vim.diagnostic.config({
    update_in_insert = true,
  })

  mason.setup({
    automatic_installation = true,
    ui = {
      icons = {
        package_installed = '',
        package_pending = '',
        package_uninstalled = ''
      }
    }
  })
  -- はddcの方で2幅に設定済み
  Config.fn.setcellwidths2({0xf05d, 0xf18e})

  local capabilities = vim.lsp.protocol.make_client_capabilities()
  capabilities.textDocument.completion.completionItem.snippetSupport = true

  local on_attach = function(_, bufnr)
    local nnoremap =  function(key, cmd) vim.keymap.set('n', key, cmd, { buffer = bufnr, silent = true }) end
    nnoremap(',d', vim.lsp.buf.definition)
    nnoremap(',i', vim.lsp.buf.implementation)
    nnoremap(',r', vim.lsp.buf.rename)
    nnoremap(',x', vim.diagnostic.open_float)
    nnoremap(',l', vim.lsp.buf.hover)
    nnoremap(',s', vim.lsp.buf.signature_help)
    nnoremap(',a', vim.lsp.buf.code_action)
    nnoremap(',f', vim.lsp.buf.references)
  end

  mason_lspconfig.setup_handlers({ function(server_name)
    local opts = {
      on_attach = on_attach,
      capabilities = capabilities
    }
    if server_name == 'denols' then
      opts.init_options = { lint = true, unstable = true }
      opts.root_dir = util.root_pattern('deno.json', 'deno.jsonc', 'denops')
      opts.single_file_support = false
    elseif server_name == 'sumneko_lua' then
      opts.settings = {
        Lua = {
          runtime = { version = 'LuaJIT' },
          diagnostics = { globals = {'vim'} },
          workspace = { library = vim.api.nvim_get_runtime_file('', true) },
          telemetry = { enable = false },
        }
      }
    elseif server_name == 'tsserver' then
      opts.root_dir = util.root_pattern('package.json', 'node_modules')
    end
    nvim_lsp[server_name].setup(opts)
  end })
  nvim_lsp['dartls'].setup {
    on_attach = on_attach,
    capabilities = capabilities,
    root_dir = util.root_pattern('pubspec.yaml', '.dart')
  }
EOF
'''
[plugins.ftplugin]
cpp = '''
lua << EOF
  local notify = vim.notify
  vim.notify = function(msg, ...)
      if msg:match('warning: multiple different client offset_encodings') then
          return
      end
      notify(msg, ...)
  end
EOF
'''

[[plugins]]
repo = 'williamboman/mason.nvim'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'nvim-lspconfig'
