# frozen_string_literal: true

tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/core'

# brew cu
tap 'buo/cask-upgrade'

brew 'act'
brew 'arduino-cli'
brew 'bat'
brew 'cloc'
brew 'cmake'
brew 'deno'
brew 'fzf'
brew 'gcc'
brew 'gh'
brew 'ghq'
brew 'git'
brew 'go'
brew 'llvm'
brew 'mono'
brew 'neovim'
brew 'node'
brew 'nodebrew'
brew 'openjdk'
brew 'peco'
brew 'php'
brew 'plantuml'
brew 'prettier'
brew 'pstree'
brew 'pyenv'
brew 'rbenv'
brew 'ripgrep'
brew 'rustup-init'
brew 'sheldon'
brew 'texlive'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'wget'

# dart
tap 'dart-lang/dart'
brew 'dart-lang/dart/dart'

# wezterm
tap 'wez/wezterm'
cask 'wezterm'

# fonts
tap 'homebrew/cask-fonts'
cask 'font-cica'
cask 'font-hack-nerd-font'
cask 'font-plemol-jp-nf'

cask 'alfred'
cask 'alt-tab'
cask 'arduino'
cask 'coteditor'
cask 'deepl'
cask 'discord'
cask 'docker'
cask 'dotnet-sdk'
cask 'figma'
cask 'firefox'
cask 'fontforge'
cask 'github'
cask 'google-chrome'
cask 'grammarly'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'karabiner-elements'
cask 'microsoft-office'
cask 'mono-mdk-for-visual-studio'
cask 'notion'
cask 'numi'
cask 'skim'
cask 'slack'
cask 'toggl-track'
cask 'unity-hub'
cask 'visual-studio'
cask 'visual-studio-code'
cask 'zoom'

# vim: ft=ruby
