# XDG Base Directory (default)
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"

# man
export MANPAGER="vim +MANPAGER --not-a-term -"
# export MANPAGER='nvim +Man!'

typeset -Ux path fpath manpath

export LANG='ja_JP.UTF-8'
export TZ='Asia/Tokyo'
