# frozen_string_literal: true

# nix/darwin/homebrew.nix に移せてないもの

# fonts
tap 'ryota2357/pleck-jp'
cask 'pleck-jp'

cask 'chatgpt'
cask 'font-cica'
cask 'font-hack-nerd-font'
cask 'font-harano-aji'
cask 'font-plemol-jp-nf'
cask 'ollama'
cask 'unity-hub'
cask 'wireshark'

# vim: ft=ruby
