# This file is generated by _generate_nix. Do not modify it manually.
{
  "aerospace.toml" = ./. + "/aerospace.toml";
  "fd~ignore" = ./. + "/fd~ignore";
  "git~config" = ./. + "/git~config";
  "git~ignore" = ./. + "/git~ignore";
  "latexmkrc" = ./. + "/latexmkrc";
  "lazygit~config.yaml" = ./. + "/lazygit~config.yaml";
}
