# This file is generated by _generate_nix. Do not modify it manually.
{
  "alacritty.toml" = ./. + "/alacritty.toml";
  "fd~ignore" = ./. + "/fd~ignore";
  "ghostty~config" = ./. + "/ghostty~config";
  "git~config" = ./. + "/git~config";
  "git~ignore" = ./. + "/git~ignore";
  "latexmkrc" = ./. + "/latexmkrc";
  "lazygit~config.yaml" = ./. + "/lazygit~config.yaml";
  "wezterm.lua" = ./. + "/wezterm.lua";
}
