# This file is generated by _generate_nix. Do not modify it manually.
{
  "alacritty.toml" = ./. + "/alacritty.toml";
  "fd~ignore" = ./. + "/fd~ignore";
  "git~ignore" = ./. + "/git~ignore";
  "karabiner_complex_modifications.json" = ./. + "/karabiner_complex_modifications.json";
  "latexmkrc" = ./. + "/latexmkrc";
  "wezterm.lua" = ./. + "/wezterm.lua";
}
