[env]
TERM = "xterm-256color"

[window]
decorations = "none"
opacity = 1.0
startup_mode = "Fullscreen"

[scrolling]
history = 10000

[font]
builtin_box_drawing = false
size = 18.5
normal = { family = "PleckJP", style = "Regular" }
bold = { family = "PleckJP", style = "Bold" }
bold_italic = { family = "PleckJP", style = "Bold Italic" }
italic = { family = "PleckJP", style = "Italic" }

[colors]
draw_bold_text_with_bright_colors = false
cursor = { cursor = "#fffaf5", text = "CellBackground" }

[cursor]
unfocused_hollow = true
style = { blinking = "Off", shape = "Block" }

[terminal.shell]
program = "/bin/bash"
args = ["-c", '''
  tmux_connect="$HOME/.local/bin/tmux-connect"
  tmux_paths="$HOME/.nix-profile/bin/tmux"
  if [[ -x "$tmux_connect" ]]; then
    "$tmux_connect" --paths "$tmux_paths"
  else
    echo "Command not found: $tmux_connect"
    /bin/zsh
  fi
  ''']

# [[keyboard.bindings]]
# chars = "\\"
# key = "¥"
#
# [[keyboard.bindings]]
# chars = "¥"
# key = "¥"
# mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Semicolon"
mods = "Command|Shift"

[general]
live_config_reload = true
