shell = 'zsh'

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.colors]
inline = 'autoload -Uz colors && zsh-defer colors'

[plugins.typeset]
inline = 'typeset -U PATH FPATH MANPATH'

[plugins.fzf]
# To install, excute: $HOMEBREW_PREFIX/opt/fzf/install
inline = '[ -f ~/.fzf.zsh ] && zsh-defer source ~/.fzf.zsh'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
use = ["{{ name }}.zsh"]
apply = ['defer']

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['defer']

[plugins.dotfiles-sync]
local = '~/dotfiles/zsh/sync'
use = ['*.zsh']
apply = ['source']

[plugins.dotfiles-defer]
local = '~/dotfiles/zsh/defer'
use = ['*.zsh']
apply = ['defer']
