name: Setup Nix with Cachix
description: Setup Nix with Cachix configuration

inputs:
  authToken:
    description: Cachix auth token
    required: true
  skipPush:
    description: Skip Cachix push configuration
    default: 'false'

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35

    - name: Setup Cachix
      uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866 # v17
      with:
        name: ryota2357
        authToken: ${{ inputs.authToken }}
        extraPullNames: nix-community
        skipPush: ${{ inputs.skipPush }}
